### ISSUE TITLE
Ignore data from fireplaces / space heaters

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#127]
https://www.reddit.com/r/beestat/comments/c1fkyp/beestat_reports_with_fireplace_in_the_home/

> Here's a weird one that no one needs to worry about for another 6 months:
> 
> We have a house with a fireplace. We use it when we're below ~25 F in order to save money compared to resistance heating, since we have spare wood lying around to burn. Unfortunately this means the processed data from Beestat gets pretty crazy at low temperatures, and the line is pulled flatter than it should be. (EDIT: I mean the two regressions for house resistance over time and heating change in temp over time)
> 
> I don't believe there's a simple way to reject data that doesn't look right as the program needs to know what "looks right" actually means, but is there a way to introduce a lockout at low temperatures so the server does not process certain data?

**Comment by ziebelje** [comment]
This is actually something I thought a lot about but never came up with a great solution for. The problem exists for fireplaces, space heaters, and any other auxiliary heat source.
I could consider adding some sort of "ignore" temperature, but I think the real solution is to just analyze and throw out bad data. The profiles are all very linear, so it's not too hard to programmatically throw out data that is statistically outside the norm.

**Comment by coneslayer** [comment]
Kind of a related question, when calculating the resist profile, do you use data when the thermostat is in Off mode?

I'm asking because the standard operating procedure in our house is to open the windows when the outside temperature is comfortable, and turn the thermostat to Off. Then we turn it back to Auto when we close the windows. (I actually have this automated with a window switch, but we used to do the same thing manually.) Obviously, when we open the windows, we're deliberately reducing the thermal resistance of the house, so I would prefer to ignore that data.

Maybe it turns out not to matter very much, since most of the statistical power in calculating the slope comes from hot and cold outside temperatures, not mild temperatures.

**Comment by ziebelje** [comment]
The resist profile is calculated from all times when all thermostats attached to the account are off. So the graph could be slightly affected right there around those comfortable temperatures, but you're probably right that overall it makes very little difference as there is far more good data than bad.

**Comment by ziebelje** [comment]
Closing this as there are no specific action items. This is part of a larger "fix what's wrong with the temperature profiles" thing which I have copious notes and ideas on.
