### ISSUE TITLE
wont sync

### ISSUE THREAD

**Issue by theeddie** [beestat/app#129]
Authorize
We're sorry but we were unable to complete your request. Please try again.

will have permissions to view the thermostat settings and data in your account.

Application Summary:
Application Description:

**Comment by ziebelje** [comment]
Hey! This typically happens if you are logged into your ecobee account when you try to connect your ecobee to beestat. Try going to ecobee.com, then log out (or log in and then log out). Alternatively clear your cache or try from a different browser. They have some bug on their end that causes this error; happens to Google, IFTTT, and all other services, too.
