### ISSUE TITLE
Aggregate runtime week off by one

### ISSUE THREAD

**Issue by NickBolles** [beestat/app#139]
Sweet app! Just started using it. I noticed that the group by week view is off by one. (and possibly others but they are harder to see) 

Currently it's Sunday jul 21st, but the week of July 22nd lists 30+ hrs of runtime. 

Here's a screenshot of, what should be 2 weeks grouped by week's
![Screenshot_20190721-232232_Chrome](https://user-images.githubusercontent.com/7891759/61606144-77be7180-ac0e-11e9-8e65-667643238104.jpg)

![Screenshot_20190721-231524_Chrome](https://user-images.githubusercontent.com/7891759/61606074-2e6e2200-ac0e-11e9-8ebb-5f75b3b42afe.jpg)
![Screenshot_20190721-231529_Chrome](https://user-images.githubusercontent.com/7891759/61606083-39c14d80-ac0e-11e9-838e-6690dea0f531.jpg)
![Screenshot_20190721-231533_Chrome](https://user-images.githubusercontent.com/7891759/61606099-45147900-ac0e-11e9-9e3f-d233467b2b3c.jpg)

I took a quick look at the aggregate component. But didn't see anything obvious. I'll look again tomorrow when I'm not on my phone and maybe submit a PR if I find anything.

**Comment by ziebelje** [comment]
I can confirm this is an issue. It happens for other ranges as well. As an example, pick "last 2 days group by day". You'll get 3 days back because the query is just asking for all data greater than now() - 2 days. That data happens to be 48 hours spanning parts of three separate days so that's what you get back.

I'm working on tweaking the query to properly account for this.

**Comment by ziebelje** [comment]
This is almost more of a feature change than it is a bug.

The current behavior simply takes your time range (2 days) and subtracts it from now. So if it's 8pm on Wednesday, it will start getting data starting at 8pm on Monday. This can sometimes feel weird, because you selected "2 days" but your result gave you 3 days (only 4 hours of Monday though).

I debated for a while but ultimately decided to change this behavior. The reason I almost didn't change it is because if you selected "Past 1 month, group by day" on the first day of the month you will only get one result. Then the next day you will get two results, etc. I found this somewhat confusing but at the same time somewhat intuitive.

Things in favor of this change:
1. Having a solid cutoff time avoids gap-fill being invoked on the first returned set constantly. If I always cut it off at a certain day or month boundary the first column will always be more accurate.
2. You do not lose any behavior. Today everything is a constant "running" tally because of how the time shifting works. This behavior is lost in examples like "past 1 month, group by day" where every month it resets to one value, but regained because you can simply do "past 30 days, group by day".

If not a lot of that makes sense, that's ok. This is more for my own documentation than anything.

I am wrapping up testing on this and hope to get it live soon.

**Comment by ziebelje** [comment]
Changes may take up to an hour to appear as the cached responses for these API calls need to expire.

**Comment by NickBolles** [comment]
Looks good! Sorry I didn't see these earlier, I would have been interested in responding, but it looks like you figured it out!
