### ISSUE TITLE
Aggregate Runtime - 2 months bug

### ISSUE THREAD

**Issue by sup-one** [beestat/app#145]
On Aug 1 the aggregate runtime for the past two months only shows 1 month.

![Ecobee - Aggregate Runtime](https://user-images.githubusercontent.com/42840882/62305975-f86f4000-b44e-11e9-88f8-2a5d9f916c7f.png)

**Comment by ziebelje** [comment]
I'll label this as a bug, but it's only halfway one. I made this change for #139. Basically, if you pick "Past two months" you are going to get the full last month, and the full this month. Previously the behavior was that you would get the past ~60 days.

This was an issue because if, for example, you picked "Past two weeks", you could end up seeing the past two weeks plus part of a third week. It was highly dependent on how you were grouping your data.

So I made the choice to change the logic. If you want the original behavior you can use the custom settings and set it to the past 60 days instead of past 2 months. I think I will actually change the default settings to do that. :)

Make sense?

**Comment by ziebelje** [comment]
I've made some adjustments to this in the next release to make it more intuitive. The past 2 months grouped by day will now just give you the past 60 days grouped by day.
