### ISSUE TITLE
Offline SeLf Hosted w/ MQTT Support 

### ISSUE THREAD

**Issue by triDcontrols** [beestat/app#15]
An idea for the future to adapt the software to be able to connect to a MQTT broker and feed the required data from any automation system and to be able to self host.

**Comment by ziebelje** [comment]
Could you elaborate a bit? I'm not very familiar with MQTT.

Are you wanting to run beestat on a local web server, then use that server to send/receive MQTT messages? What things would you want to do with those messages? Send messages to control your thermostat from other MQTT devices in your IOT? Have beestat fire off alerts, etc to other devices?

**Comment by ziebelje** [comment]
https://www.hackster.io/bkpsu/nodemcu-remote-multisensor-with-oled-mqtt-440f09

**Comment by ziebelje** [comment]
At present I have decided not to pursue open sourcing or anything like MQTT. It's a lot of work to prepare and maintain that. My time is better spent on fleshing out the current features and working on some of the data analysis that I've always wanted to improve. Also, I'm not as interested in those things from a personal perspective and development on the project would suffer and become a chore instead of fun.

Anyone interested in pursuing a project like this can check out [sqlbee](https://github.com/ziebelje/sqlbee). I'll keep an eye on future interest in this and reevaluate when I feel like I've accomplished all my goals.

**Comment by ziebelje** [comment]
Note that I am open-sourcing beestat soon, but have no immediate plans for MQTT support.

If I did this in the future, I would have to add a way to subscribe to a MQTT broker. The biggest concern I have with that type of implementation is that pinging the broker would have to be done every 5 minutes, as I believe a broker will only store the most recent message.

That's not particularly difficult, but right now I am able to rely a bit on ecobee's historical data to fill in any gaps from downtime or errors. So this would have to be pretty robust. Self-hosting would be a separate deal from all this...the implementation is the same regardless.
