### ISSUE TITLE
Stuck on connect page

### ISSUE THREAD

**Issue by lsbrodsky** [beestat/app#162]
After the update, I have cleared my cache and cookies, delted the app on Ecobee, but I am stuck on the "connect" page for beestat. I click on connect and nothing happens.
Larry

**Comment by ziebelje** [comment]
Issue appears to be an old cookie being present and not getting cleared. Then when loading app.beestat.io it does an API call which fails because of the old invalid cookie, which redirects back to beestat.io. Related to #161. Marking this one as closed for now because I verified that the home page was deleting those cookies but this particular situation was still getting a cached version of the home page which was not deleting those cookies.
