### ISSUE TITLE
Looking for way to omit bad data from reporting.

### ISSUE THREAD

**Issue by jsokoloski** [beestat/app#210]
My furnace had a issue over a couple days where the ecobee was calling for heat, but the furnace wasn't delivering. I think this has cause issues with some of the reports. Is there a way to omit this "bad data" from reporting.

Thanks!

**Comment by ziebelje** [comment]
If you email a date range and serial number to contact@beestat.io I can manually delete the data, but that'd be it. Doing this will remove the data from beestat, causing it to be blank on the Runtime charts and not available for use in any temperature profile/score calculations.

I'll close this since it will need to be resolved over email if you want to proceed.
