### ISSUE TITLE
Authorization failures

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#269]
Looks like ecobee broke something with 2FA. Beestat will not authorize when it is enabled...same for other third party services.

**Comment by jharlap** [comment]
We’ve been working on updating our authentication system to add support for 2FA, and in the process have changed our access token format from the legacy 32 character format to JWT, which can be much longer and uses a wider character set. We’ll soon be communicating this breaking API change to all developers, along with updated documentation to assist with migration and updated tooling via our web portal. If you don’t want to wait for that and are sure that your app will not break if given JWTs instead of the legacy access tokens, I’d be happy to add your app to our early access program. If you're interested in that, please open a ticket at https://ecobee.atlassian.net/servicedesk/customer/portal/5 and we can share the details there.

**Comment by ziebelje** [comment]
@jharlap Thanks for chiming in. I've been in maintenance mode for a while and haven't really been actively pursuing this. I'll be diving in soon.

In the meantime...did ecobee fix #44? I was just re-testing that and noticed that when I was already logged into ecobee it now correctly picks up that session in the oauth flow.

Although...after authorizing it redirects me to the ecobee home page and signs me out.

![2020-06-09_22-18-25](https://user-images.githubusercontent.com/3288812/84219807-591fce00-aa9f-11ea-9765-f747212659c3.gif)

**Comment by ziebelje** [comment]
Also @jharlap, I opened a ticket to explore your early access program (DEVAPISUPP-155). Thanks!
