### ISSUE TITLE
Aggregate data from multiple thermostats

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#29]
> I was wondering if it was possible to aggregate the data from multiple thermostats into one analysis. My home has four separate thermostats and I'd love to have all the data in one place.

**Comment by k1n6b0b** [comment]
I second this! I *assume* because I have multiple zones on my boiler that this drastically affects the "efficiency" shown when only considering a zone independently?

**Comment by acesarewld** [comment]
Giant +1 to this as well. Just got 4 EcoBee's installed and the data I can collect is awesome, but I don't have a way to see it *ALL* in one place at once time

**Comment by ziebelje** [comment]
@k1n6b0b The beestat Home Efficiency chart is based on each individual thermostat. The 1.3 update (coming soon...) fixes that by grouping thermostats by physical address.
@acesarewld or anyone else...would love some feedback on exactly how you would prefer to see this data aggregated. Do you want one chart per thermostat? Somehow group all thermostats into a single chart? Something else entirely?

**Comment by acesarewld** [comment]
> @acesarewld or anyone else...would love some feedback on exactly how you would prefer to see this data aggregated. Do you want one chart per thermostat? Somehow group all thermostats into a single chart? Something else entirely?

Thanks for writing back! I meant to send this sooner -- but with EcoBee being DOWN for the last 2 weeks I've been trying to adjust my system with very minimal data to work from.

Anyway, I'd like something of a whole-house dashboard, like Home Assistant https://www.home-assistant.io) provides but FAR FAR FAR LESS COMPLICATED! 

So a bulleted list of ideas for what I was looking for includes:
    • Dashboard view with all thermostats and sensors connected to them
    • AJAX-style auto-update and auto load when new data is available
    • Scrolling left/right of graph data like HomeIQ page has (I know using highcharts may prevent this)
    • Ability to see all thermostat data at once (a whole-house view)
	-Is a single graph with all data (minus redundant data like outside temp) the correct answer?
	-Is a stacked set of graphs per-thermostat a better implementation?
    • Mouse-over icons should have tooltips explaining what the icons mean

Ultimately the dashboard for my 4 thermostats should include things like runtime since 12:00AM that day, current temps, current humidity, and what equipment is running [and why it is/isn't running — recovery? temp trigger? away mode? etc..]

It may be nice to have something we could install/host ourselves to alleviate pressure on your servers and hosting capabilities as well.

Anyway, these were just some basic thoughts -- your service is GREAT and thank you for offering it to us!

**Comment by ziebelje** [comment]
Another request: https://community.beestat.io/t/combine-thermostat-graphs-on-a-single-graph-page/187/1

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/combine-data-from-multiple-thermostats-onto-a-single-chart/187
