### ISSUE TITLE
Slider popup behavior when data missing

### ISSUE THREAD

**Issue by GMart** [beestat/app#345]
**Describe the bug**
Slider popup does not move correctly when there is a gap in data on graphs

**To Reproduce**
Have gap in data
Slide mouse cursor back and forth
Popup will not always lag behind the direction the mouse is moving. It sometimes appears to be in the middle of the slider bar. It also glitches around instead of always appearing to the left or right of the line.
It appears on the sensor graph and the thermostat detail graphs.

**Screenshot**
![Screenshot 2021-11-07 Beestat](https://user-images.githubusercontent.com/5506540/140650531-06ae0dae-d07a-426b-b7ca-847c4de73b0d.png)

**Comment by GMart** [comment]
I would also like to add a related bug:
On the mobile page, the detail popup stays up when you remove your finger from the graph. I have to tap the graph area, then a blank space so the detail popup will disappear.
Otherwise, this is a great piece of software, thanks for developing it!
- Fellow Hoosier

**Comment by ziebelje** [comment]
I can confirm this bug. The reason for the jitter is because the tooltip is trying to position itself relative to the nearest point, which is to the left or right quite a bit. This starts to happen, but then the tooltip tries to position itself again because there are also hidden points for other purposes.

If I get really bored one day maybe I'll try to fix this one. ;)

As for the mobile tooltip not going away...you're right but I don't think you want it to go away. I tried having it disappear automatically after a few seconds on mobile but then if you're actually looking at the tooltip data it disappears on you. I think the better option is to just show it always on mobile until you click outside the graph. If you have any other ideas let me know.

**Comment by GMart** [comment]
Thanks for looking into it!
I think the issue with the mobile tooltip is that is stays even when I start scrolling. Could there be a threshold, so that when you start scrolling at a certain speed or higher, it hides the tooltip? Right now it seems to need two separate taps outside the graph area to hide. (I'm on Android 11, Chrome browser)

Happy Holidays!
