### ISSUE TITLE
IAQ values above 255 don't get stored

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#365]
If ecobee sends a value above 255 for IAQ the value is not stored because the database column doesn't support it. Need to alter database table to fix.

**Comment by robsters** [comment]
Joe - Noticed that this update caused an issue on mine that I had to fix in MySQL since the database fields were tinyint.  Noticed that the beestat.sql template didn't get updated online.  Should the .sql file be updated?   Fixed mine manually in the database for two fields, but figured you might want to know about that..  It's possible I'm looking at the wrong file on github.

**Comment by ziebelje** [comment]
Whoops - not used to having anyone self-hosting. My oversight! Updated SQL...three fields changed. You can find the updates in the beestat.sql file linked in the above commit.

**Comment by robsters** [comment]
LOL.  Thanks Joe!  Working on making this quick to self-host using docker, when I started running into errors after spinning up MySQL in docker and pointing the php scripts to that, I was like that's strange..
