### ISSUE TITLE
Authentication breaks if you're already logged in.

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#44]
![image](https://user-images.githubusercontent.com/3288812/42956597-62348c1e-8b4e-11e8-9792-bb837bbf0ece.png)

**Comment by Valien** [comment]
As an interim fix for users wondering how to get Beestat going:

1. Log out of your ecobee account
2. Go to beestat.io and click the button to register your ecobee
3. The API should direct you to the ecobee login page. Login and you should be connected!

**Comment by ziebelje** [comment]
I submitted a ticket to ecobee about this finally. It affects other services like IFTTT and Google Home. Fingers crossed.

**Comment by rct** [comment]
Still seems to be an issue as of Jan 2019 - Glad I found this issue to figure it out.   

Probably should be a separate issue, but I think a better UX would be that clicking the Ecobee button takes you to an explanation page first that tells the user what is going to happen and how to link their account.  Also would be a good place to temporarily mention that you need to be logged out in order to sign up.

**Comment by ziebelje** [comment]
Agree mostly! I always consider how difficult it will make something to use. While this is not hard, showing a new page with text to read and another button to click is going to put some people off. For a paid service losing that conversion is a big deal, but maybe for beestat (a free service) it's more important to present that information. I'll give it some more thought!

**Comment by ziebelje** [comment]
Merging into #269.
