### ISSUE TITLE
Support for dual enegy/dual rate-feature request

### ISSUE THREAD

**Issue by mvonh** [beestat/app#94]
Hello,

It would be super useful for users of Dual-Energy and dual-rate  systems (hyrdro-Quebec and maybe others) to have a colour indication of when the outdoor temp is below a certain amount (-12) vs above.  This is good to know as at that temp. our system is set to switch-over from heatpump, to oil (or gas).

**Comment by ziebelje** [comment]
Is this temperature a setting on your ecobee or is it some other configuration/property of your equipment?

**Comment by mvonh** [comment]
Hi, no it's not on the ecobee, its an external relay that is connected to the hydro meter (it has an external temp sensor) which does the switch from heatpump to aux (oil in my case).  The dual rate is to encourage less use of hydro when very cold, hence the switch to oil or gas, and when milder (above -12c), we are billed at a much lower rate, so heatpump becomes very economical.  It's very common in Quebec.  I was just thinking that if the ext. temp. graph could be color coded at the threshold it would  helpful to visually when running on oil vs heatpump.

**Comment by ziebelje** [comment]
Makes sense! Something like this would be pretty easy to add...I just don't have a spot for it right now. When I get around to some of the customization features I'll look into adding the ability to either define this explicitly or add some other generic threshold line/color for it.

**Comment by buzzydabee** [comment]
Hi, 

I'm also on this dual-rate program from hydro-quebec (in french its called bi-energie). 

Adding to mvonh suggestion, it would be great to allow to break the heating trendline of the temperature profile in 2 separate segments, each having its own regression process. In our case, the breaking point would be at the rating-change temperature of -12C, and would allow exact evaluation of the efficiency of both heating system, rather than having some king of averaged trend. 

Note that the shift from one heating system to the other is manage at the HVAC level, using the temperature provided by an exterior HQ probe and some mystical regional averaging. This to say that Ecobee setting might not be a reliable source of input to detect this kind of setup. I guess this would leave you with the option of dual-trendline checkbox option, with a user defined breaking point temperature... 

As a final note:
I fiddled quite a bit to try to make Ecobee believe it was in charge by using the same wire for what ecobee believe to be a heat pump and aux furnace. This allow me to get seperate stats from ecobee, but it lacks some precision since the shift from compressor to Aux cant be set to exactly -12C (stepwise setting) and its also impossible to get ecobee to use the exact same external temperature that HQ is using.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/support-for-dual-enegy-dual-rate/327
